# This schema definition is available in the public domain, or under the terms
# of CC-0, at your choice.

# String of the format %Y-%m-%dT%H:%M:%SZ
scalar Time
# Opaque string
scalar Cursor
# URL from which some secondary data may be retrieved. You must provide the
# same Authentication header to this address as you did to the GraphQL resolver
# which provided it.
scalar URL

# Used to provide a human-friendly description of an access scope
directive @scopehelp(details: String!) on ENUM_VALUE

enum AccessScope {
  ACLS          @scopehelp(details: "access control lists")
  EMAILS        @scopehelp(details: "emails")
  LISTS         @scopehelp(details: "mailing lists")
  PATCHES       @scopehelp(details: "patches")
  PROFILE       @scopehelp(details: "profile information")
  SUBSCRIPTIONS @scopehelp(details: "tracker & ticket subscriptions")
}

enum AccessKind {
  RO @scopehelp(details: "read")
  RW @scopehelp(details: "read and write")
}

# Decorates fields for which access requires a particular OAuth 2.0 scope with
# read or write access.
directive @access(scope: AccessScope!, kind: AccessKind!) on FIELD_DEFINITION

# This used to decorate private resolvers which are only accessible to build
# workers, and are used to facilitate the build process.
directive @worker on FIELD_DEFINITION

# https://semver.org
type Version {
  major: Int!
  minor: Int!
  patch: Int!

  # If this API version is scheduled for deprecation, this is the date on which
  # it will stop working; or null if this API version is not scheduled for
  # deprecation.
  deprecationDate: Time
}

interface Entity {
  canonicalName: String!
}

# A registered user
type User implements Entity {
  id: Int!
  created: Time!
  updated: Time!
  canonicalName: String!
  username: String!
  email: String!
  url: String
  location: String
  bio: String

  lists(cursor: Cursor): MailingListCursor @access(scope: LISTS, kind: RO)
  emails(cursor: Cursor): EmailCursor @access(scope: EMAILS, kind: RO)
  threads(cursor: Cursor): ThreadCursor @access(scope: EMAILS, kind: RO)
  patches(cursor: Cursor): PatchsetCursor @access(scope: PATCHES, kind: RO)
}

# A mailbox not associated with a registered user
type Mailbox implements Entity {
  canonicalName: String!
  name: String!
  address: String!
}

type MailingList {
  id: Int!
  created: Time!
  updated: Time!
  name: String!
  owner: Entity! @access(scope: PROFILE, kind: RO)

  # Markdown
  description: String

  # List of globs for permitted or rejected mimetypes on this list
  # e.g. text/*
  permit_mime: [String!]!
  reject_mime: [String!]!

  # List of threads on this list in order of most recently bumped
  threads(cursor: Cursor): ThreadCursor! @access(scope: EMAILS, kind: RO)
  # List of emails received on this list in reverse chronological order
  emails(cursor: Cursor): EmailCursor! @access(scope: EMAILS, kind: RO)
  # List of patches received on this list in order of most recently bumped
  patches(cursor: Cursor): PatchsetCursor! @access(scope: PATCHES, kind: RO)

  # True if an import operation is underway for this list
  importing: Boolean!

  # The access that applies to this user for this list
  access: ACL!

  # The user's subscription for this list, if any
  subscription: Subscription

  # URLs to application/mbox archives for this mailing list
  archive: URL!
  last30days: URL!
}

interface ACL {
  # Permission to browse or subscribe to emails
  browse: Boolean!
  # Permission to reply to existing threads
  reply: Boolean!
  # Permission to start new threads
  post: Boolean!
  # Permission to moderate the list
  moderate: Boolean!
}

# These ACLs are configured for specific entities, and may be used to expand or
# constrain the rights of a participant.
type MailingListACL implements ACL {
  id: Int!
  created: Time!
  list: MailingList! @access(scope: LISTS, kind: RO)
  entity: Entity! @access(scope: PROFILE, kind: RO)

  browse: Boolean!
  reply: Boolean!
  post: Boolean!
  moderate: Boolean!
}

# An ACL entry that applies "generally", for example the rights which apply to
# all subscribers to a list.
type GeneralACL implements ACL {
  browse: Boolean!
  reply: Boolean!
  post: Boolean!
  moderate: Boolean!
}

type Thread {
  created: Time!
  updated: Time!
  subject: String!
  replies: Int!
  participants: Int!
  sender: Entity!

  root: Email!

  list: MailingList! @access(scope: LISTS, kind: RO)

  # Replies to this thread, in chronological order
  descendants(cursor: Cursor): EmailCursor!

  # A mailto: URI for replying to the latest message in this thread
  mailto: String!

  # URL to an application/mbox archive of this thread
  mbox: URL!
}

type Email {
  id: Int!

  # The entity which sent this email. Will be a User if it can be associated
  # with an account, or a Mailbox otherwise.
  sender: Entity!
  # Time we received this email (non-forgable).
  received: Time!
  # Time given by Date header (forgable).
  date: Time
  # The Subject header.
  subject: String!
  # The Message-ID header, without angle brackets.
  message_id: String!
  # The In-Reply-To header, if present, without angle brackets.
  in_reply_to: String

  # Provides the value (or values) of a specific header from this email. Note
  # that the returned value is coerced to UTF-8 and may be lossy under certain
  # circumstances.
  header(want: String!): [String!]!
  # Retrieves the value of an address list header, such as To or Cc.
  address_list(want: String!): [Mailbox!]!
  # The decoded text/plain message part of the email, i.e. email body.
  body: String!
  # A URL from which the full raw message envelope may be downloaded.
  envelope: URL!

  thread: Thread!
  parent: Email
  patch: Patch

  patchset: Patchset @access(scope: PATCHES, kind: RO)
  list: MailingList! @access(scope: LISTS, kind: RO)
}

# Information parsed from the subject line of a patch, such that the following:
#
#   [PATCH myproject v2 3/4] Add foo to bar
#
# Will produce:
#
# index: 3
# count: 4
# version: 2
# prefix: "myproject"
# subject: "Add foo to bar"
type Patch {
  index: Int
  count: Int
  version: Int
  prefix: String
  subject: String
}

enum PatchsetStatus {
  UNKNOWN
  PROPOSED
  NEEDS_REVISION
  SUPERSEDED
  APPROVED
  REJECTED
  APPLIED
}

type Patchset {
  id: Int!
  created: Time!
  updated: Time!
  subject: String!
  version: Int!
  prefix: String
  status: PatchsetStatus!
  submitter: Entity!

  cover_letter: Email
  thread: Thread!
  superseded_by: Patchset
  list: MailingList! @access(scope: LISTS, kind: RO)
  patches(cursor: Cursor): EmailCursor!
  tools: [PatchsetTool!]!

  # URL to an application/mbox archive of only the patches in this thread
  mbox: URL!
}

enum ToolIcon {
  PENDING
  WAITING
  SUCCESS
  FAILED
  CANCELLED
}

# Used to add some kind of indicator for a third-party process associated with
# a patchset, such as a CI service validating the change.
type PatchsetTool {
  id: Int!
  created: Time!
  updated: Time!
  icon: ToolIcon!
  details: String!
  key: String!
  patchset: Patchset!
}

interface Subscription {
  id: Int!
  created: Time!
}

type MailingListSubscription implements Subscription {
  id: Int!
  created: Time!
  list: MailingList! @access(scope: LISTS, kind: RO)
}

# A cursor for enumerating mailing lists
#
# If there are additional results available, the cursor object may be passed
# back into the same endpoint to retrieve another page. If the cursor is null,
# there are no remaining results to return.
type MailingListCursor {
  results: [MailingList!]!
  cursor: Cursor
}

# A cursor for enumerating threads
#
# If there are additional results available, the cursor object may be passed
# back into the same endpoint to retrieve another page. If the cursor is null,
# there are no remaining results to return.
type ThreadCursor {
  results: [Thread!]!
  cursor: Cursor
}

# A cursor for enumerating emails
#
# If there are additional results available, the cursor object may be passed
# back into the same endpoint to retrieve another page. If the cursor is null,
# there are no remaining results to return.
type EmailCursor {
  results: [Email!]!
  cursor: Cursor
}

# A cursor for enumerating patchsets
#
# If there are additional results available, the cursor object may be passed
# back into the same endpoint to retrieve another page. If the cursor is null,
# there are no remaining results to return.
type PatchsetCursor {
  results: [Patchset!]!
  cursor: Cursor
}

# A cursor for enumerating subscriptions
#
# If there are additional results available, the cursor object may be passed
# back into the same endpoint to retrieve another page. If the cursor is null,
# there are no remaining results to return.
type SubscriptionCursor {
  results: [Subscription!]!
  cursor: Cursor
}

type Query {
  # Returns API version information
  version: Version!

  # Returns the authenticated user
  me: User! @access(scope: PROFILE, kind: RO)

  # Looks up a specific user
  user(id: Int!): User @access(scope: PROFILE, kind: RO)
  userByName(username: String!): User @access(scope: PROFILE, kind: RO)

  # Looks up a specific mailing list
  mailingList(id: Int!): MailingList @access(scope: LISTS, kind: RO)
  mailingListByName(name: String!): MailingList @access(scope: LISTS, kind: RO)
  mailingListByOwner(ownerName: String!, listName: String!): MailingList @access(scope: LISTS, kind: RO)

  # Looks up a specific email by its ID
  email(id: Int!): Email @access(scope: EMAILS, kind: RO)
  # Looks up a specific email by its Message-ID header, including the angle
  # brackets ('<' and '>').
  message(messageID: String!): Email @access(scope: EMAILS, kind: RO)
  # Looks up a patchset by ID
  patchset(id: Int!): Patchset @access(scope: EMAILS, kind: RO)

  # List of mailing lists that the authenticated user has ownership of
  mailingLists(cursor: Cursor): MailingListCursor! @access(scope: LISTS, kind: RO)

  # List of subscriptions of the authenticated user
  subscriptions(cursor: Cursor): SubscriptionCursor @access(scope: SUBSCRIPTIONS, kind: RO)
}
